# Codecov configuration for Rediacc CLI
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto

  changes:
    default:
      base: auto

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  Linux-py3.8:
    carryforward: true
  Linux-py3.9:
    carryforward: true
  Linux-py3.10:
    carryforward: true
  Linux-py3.11:
    carryforward: true
  Linux-py3.12:
    carryforward: true
  Linux-py3.13:
    carryforward: true

  macOS-py3.8:
    carryforward: true
  macOS-py3.9:
    carryforward: true
  macOS-py3.10:
    carryforward: true
  macOS-py3.11:
    carryforward: true
  macOS-py3.12:
    carryforward: true

  Windows-py3.8:
    carryforward: true
  Windows-py3.9:
    carryforward: true
  Windows-py3.10:
    carryforward: true
  Windows-py3.11:
    carryforward: true
  Windows-py3.12:
    carryforward: true

ignore:
  - "tests/**/*"
  - "**/__pycache__/**/*"
  - "**/test_*.py"
  - "**/*_test.py"
  - "setup.py"
  - "docs/**/*"
  - "examples/**/*"
  - "scripts/**/*"
