services:
  # Development service
  rediacc-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rediacc-cli-dev
    volumes:
      - .:/app
      - go-cache:/app/.cache
    working_dir: /app
    environment:
      - GO_ENV=development
      - REDIACC_SERVER_URL=http://rediacc-api:80/api
    networks:
      - rediacc-network
    profiles:
      - dev
    stdin_open: true
    tty: true

  # Production service
  rediacc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rediacc-cli
    environment:
      - GO_ENV=production
      - REDIACC_SERVER_URL=http://rediacc-api:80/api
    networks:
      - rediacc-network
    profiles:
      - prod

  # Optional: Mock middleware for testing
  middleware-mock:
    image: nginx:alpine
    container_name: rediacc-middleware-mock
    volumes:
      - ./tests/fixtures/mock-server.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rediacc-network
    profiles:
      - test

volumes:
  go-cache:
    driver: local

networks:
  rediacc-network:
    driver: bridge