name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  lint-build-test:
    name: lint+build+test (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip wheel setuptools build

      - name: Install dev dependencies
        run: |
          python -m pip install mypy flake8 black

      - name: Editable install (dev)
        run: |
          python -m pip install -e ".[dev]"

      - name: Type check (targeted)
        run: |
          # Limit scope and skip following imports to avoid repo-wide failures
          python -m mypy src/cli/setup_hooks.py src/cli/__init__.py src/cli/_setup_cmds.py \
            --ignore-missing-imports --no-strict-optional --follow-imports=skip --python-version=3.9

      - name: Lint (targeted)
        run: |
          black --check setup.py src/cli/__init__.py src/cli/setup_hooks.py src/cli/_setup_cmds.py
          flake8 setup.py src/cli/__init__.py src/cli/setup_hooks.py src/cli/_setup_cmds.py

      - name: Build sdist and wheel
        run: |
          python -m build
          ls -la dist || dir dist

      - name: Install built wheel (overwrite editable) and smoke test CLI
        run: |
          python -m pip install --force-reinstall --no-deps dist/*.whl
          # Run via module to avoid PATH-specific differences across OS shells
          python -m cli.commands.cli_main --help