name: CLI Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual triggers

# Set permissions for GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  # Linux tests - all Python versions sequentially with shared Elite backend
  test-linux:
    name: Linux Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Start Elite Services
        uses: rediacc/elite/action@main
        with:
          keep-alive: 'true'
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Install Cloudflare Tunnel
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Configure UDP Buffer Sizes
        run: |
          sudo sysctl -w net.core.rmem_max=7500000
          sudo sysctl -w net.core.wmem_max=7500000

      - name: Start Cloudflare Tunnel
        id: tunnel
        run: |
          MAX_RETRIES=3
          RETRY_COUNT=0
          TUNNEL_URL=""

          while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ -z "$TUNNEL_URL" ]; do
            echo "Tunnel creation attempt $((RETRY_COUNT + 1))/$MAX_RETRIES..."

            # Kill any existing cloudflared process
            pkill -f cloudflared || true
            sleep 2

            # Remove old log
            rm -f /tmp/cloudflared.log

            # Start cloudflared tunnel in background
            cloudflared tunnel --url http://localhost --logfile /tmp/cloudflared.log &
            TUNNEL_PID=$!
            echo "Started cloudflared with PID: $TUNNEL_PID"

            # Wait for tunnel to register connection (success indicator)
            for i in {1..30}; do
              # Check if tunnel connection is registered (key success indicator)
              if grep -q 'Registered tunnel connection' /tmp/cloudflared.log 2>/dev/null; then
                echo "✓ Tunnel connection registered"

                # Extract URL from logs
                TUNNEL_URL=$(grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' /tmp/cloudflared.log | head -1)
                if [ -n "$TUNNEL_URL" ]; then
                  echo "url=$TUNNEL_URL" >> $GITHUB_OUTPUT
                  echo "tunnel_pid=$TUNNEL_PID" >> $GITHUB_OUTPUT
                  echo "✓ Tunnel URL obtained: $TUNNEL_URL"
                  break 2  # Break out of both loops
                fi
              fi

              # Check for REAL API errors (ignore certificate warnings)
              if grep '"level":"error"' /tmp/cloudflared.log 2>/dev/null | grep -v 'origincert' | grep -v 'origin certificate' | grep -q '.'; then
                echo "⚠ Real API error detected in logs"
                break
              fi

              sleep 2
            done

            # If we didn't get a URL, check logs and retry
            if [ -z "$TUNNEL_URL" ]; then
              echo "Failed to get tunnel URL on attempt $((RETRY_COUNT + 1))"

              # Check for real API errors (not certificate warnings)
              if grep '"level":"error"' /tmp/cloudflared.log 2>/dev/null | grep -v 'origincert' | grep -v 'origin certificate' | grep -q '.'; then
                echo "Cloudflare API error detected, retrying..."
                grep '"level":"error"' /tmp/cloudflared.log | grep -v 'origincert' | grep -v 'origin certificate' | head -3
              fi

              kill $TUNNEL_PID 2>/dev/null || true
              RETRY_COUNT=$((RETRY_COUNT + 1))
              sleep 5
            fi
          done

          # Final check
          if [ -z "$TUNNEL_URL" ]; then
            echo "✗ Failed to create tunnel after $MAX_RETRIES attempts"
            echo "=== Last cloudflared.log ==="
            cat /tmp/cloudflared.log || true
            exit 1
          fi

      - name: Verify Tunnel
        run: |
          TUNNEL_URL="${{ steps.tunnel.outputs.url }}"
          echo "Verifying tunnel at: $TUNNEL_URL"

          if [ -z "$TUNNEL_URL" ]; then
            echo "Failed to get tunnel URL"
            cat /tmp/cloudflared.log
            exit 1
          fi

          for i in {1..20}; do
            if curl -f "$TUNNEL_URL/api/health" 2>/dev/null; then
              echo "✓ Tunnel verified and accessible"
              exit 0
            fi
            echo "Attempt $i/20..."
            sleep 3
          done

          echo "Failed to verify tunnel"
          cat /tmp/cloudflared.log
          exit 1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xdg-utils rsync openssh-client desktop-file-utils xvfb python3-tk python3-dev

      - name: Test Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'

      - name: Run tests Python 3.8
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          xvfb-run -a -s "-screen 0 1920x1080x24" python -m pytest tests/ -v --cov=cli --cov-report=xml --cov-report=html --junitxml=test-results-3.8/junit.xml --tb=short
        env:
          SYSTEM_API_URL: ${{ steps.tunnel.outputs.url }}/api
          SYSTEM_ADMIN_EMAIL: admin@rediacc.io
          SYSTEM_ADMIN_PASSWORD: admin
          REDIACC_TEST_ACTIVATION_CODE: "111111"
          API_TIMEOUT: 60

      - name: Integration tests Python 3.8
        working-directory: tests
        run: ./run_integration_ci.sh
        env:
          SYSTEM_API_URL: ${{ steps.tunnel.outputs.url }}/api
          SYSTEM_ADMIN_EMAIL: admin@rediacc.io
          SYSTEM_ADMIN_PASSWORD: admin
          REDIACC_TEST_ACTIVATION_CODE: "111111"
          API_TIMEOUT: 60

      - name: Setup Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Run tests Python 3.9
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          xvfb-run -a -s "-screen 0 1920x1080x24" python -m pytest tests/ -v --cov=cli --cov-report=xml --cov-report=html --junitxml=test-results-3.9/junit.xml --tb=short

      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run tests Python 3.10
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          xvfb-run -a -s "-screen 0 1920x1080x24" python -m pytest tests/ -v --cov=cli --cov-report=xml --cov-report=html --junitxml=test-results-3.10/junit.xml --tb=short

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Run tests Python 3.11
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          xvfb-run -a -s "-screen 0 1920x1080x24" python -m pytest tests/ -v --cov=cli --cov-report=xml --cov-report=html --junitxml=test-results-3.11/junit.xml --tb=short

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run tests Python 3.12
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          xvfb-run -a -s "-screen 0 1920x1080x24" python -m pytest tests/ -v --cov=cli --cov-report=xml --cov-report=html --junitxml=test-results-3.12/junit.xml --tb=short

      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run tests Python 3.13
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          xvfb-run -a -s "-screen 0 1920x1080x24" python -m pytest tests/ -v --cov=cli --cov-report=xml --cov-report=html --junitxml=test-results-3.13/junit.xml --tb=short

      - name: Cleanup
        if: always()
        run: |
          kill ${{ steps.tunnel.outputs.tunnel_pid }} 2>/dev/null || true
          docker ps -a --filter "name=rediacc-" --format "{{.Names}}" | xargs -r docker stop || true
          docker ps -a --filter "name=rediacc-" --format "{{.Names}}" | xargs -r docker rm || true

  # Windows tests - sequential after Linux
  test-windows:
    name: Windows Tests
    runs-on: windows-latest
    needs: test-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Setup headless display for GUI testing (tkinter, etc.)
      # Uses Mesa3D offscreen rendering to enable GUI tests on headless Windows runners
      - name: Setup Headless Display
        uses: pyvista/setup-headless-display-action@v3
        with:
          mesa3d-release: 24.3.0
          install-mesa3d-offscreen: true
          pyvista: false

      - name: Install system dependencies
        run: choco install rsync openssh -y
        shell: pwsh

      - name: Setup Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'

      - name: Run tests Python 3.8
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short
        shell: bash

      - name: Setup Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Run tests Python 3.9
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short
        shell: bash

      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run tests Python 3.10
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short
        shell: bash

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Run tests Python 3.11
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short
        shell: bash

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run tests Python 3.12
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short
        shell: bash

  # macOS tests - sequential after Windows
  test-macos:
    name: macOS Tests
    runs-on: macos-latest
    needs: test-windows

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install system dependencies
        run: brew install duti || true

      - name: Setup Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'

      - name: Run tests Python 3.8
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short

      - name: Setup Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Run tests Python 3.9
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short

      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run tests Python 3.10
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Run tests Python 3.11
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run tests Python 3.12
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[test,dev]"
          python -m pytest tests/ -v --cov=cli --cov-report=xml --tb=short

  # Code quality checks
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run checks
        run: |
          black --check src/ tests/ || true
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics || true
          mypy src/cli --ignore-missing-imports || true

  # Test summary
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-linux, test-windows, test-macos, code-quality]
    if: always()

    steps:
      - name: Check results
        run: |
          echo "Linux: ${{ needs.test-linux.result }}"
          echo "Windows: ${{ needs.test-windows.result }}"
          echo "macOS: ${{ needs.test-macos.result }}"

          if [ "${{ needs.test-linux.result }}" != "success" ]; then
            echo "::error::Linux tests failed"
            exit 1
          fi

          if [ "${{ needs.test-windows.result }}" != "success" ]; then
            echo "::error::Windows tests failed"
            exit 1
          fi

          if [ "${{ needs.test-macos.result }}" != "success" ]; then
            echo "::error::macOS tests failed"
            exit 1
          fi

          echo "✓ All tests passed!"
